<?php

declare(strict_types=1);

namespace App\Enum;

enum DocumentType: string
{
    case SOMATIE = 'somatie';
    case CERERE_OP = 'cerere_op';
    case OPIS = 'opis';
    case ORDONANTA_PLATA = 'ordonanta_plata';
    case DOVADA_COMUNICARE = 'dovada_comunicare';
    case DOVADA_TAXA_TIMBRU = 'dovada_taxa_timbru';
    case ACT_CONSTATATOR = 'act_constatator';
    case ANEXA = 'anexa';
    case DOVADA = 'dovada';
    case CONTRACT = 'contract';
    case FACTURA = 'factura';
    case BPI_PROOF = 'bpi_proof';
    case EXTRAS_CONT = 'extras_cont';
    case CONFIRMARE_SOLD = 'confirmare_sold';
    case PROCES_VERBAL = 'proces_verbal';
    case COMANDA = 'comanda';
    case NOTIFICARE = 'notificare';
    // Distinct from SOMATIE: that one is generated by the platform and never
    // uploadable, while this is a demand letter the lawyer already sent and
    // now files as evidence.
    case SOMATIE_ANTERIOARA = 'somatie_anterioara';
    case ACT_ADITIONAL = 'act_aditional';
    case TITLU_VALOARE = 'titlu_valoare';
    case ALT_DOCUMENT = 'alt_document';

    public function label(): string
    {
        return 'enum.document_type.' . $this->value;
    }

    /**
     * Generate de aplicație prin `AbstractPdfGenerator::generate()` — NU se
     * upload-ează niciodată de avocat ca documente sursă. Single source of
     * truth pentru split UI „Documente generate" vs „Documente sursă" și
     * pentru `CaseFilesPackager` (numerotare top-level vs `anexe/`).
     */
    public function isAutoGenerated(): bool
    {
        return match ($this) {
            self::SOMATIE, self::CERERE_OP, self::OPIS => true,
            default => false,
        };
    }

    /**
     * Uploaded through a dedicated flow, not the generic document modal. The
     * stamp-duty proof carries payment state (status, payer, amount, UAT snapshot)
     * that only `CaseStampDutyController` knows how to record, so offering it in
     * the generic dropdown would silently produce a proof with no payment behind it.
     */
    public function hasDedicatedUploadFlow(): bool
    {
        return $this === self::DOVADA_TAXA_TIMBRU;
    }

    /**
     * Non-auto-generated types available for lawyer upload. Single source of truth
     * for both the upload form choices and the upload modal options.
     *
     * @return self[]
     */
    public static function uploadableTypes(): array
    {
        return array_values(array_filter(
            self::cases(),
            static fn (self $type): bool => !$type->isAutoGenerated() && !$type->hasDedicatedUploadFlow(),
        ));
    }
}
