<?php

declare(strict_types=1);

namespace App\Enum;

enum DocumentType: string
{
    case SOMATIE = 'somatie';
    case CERERE_OP = 'cerere_op';
    case OPIS = 'opis';
    case ORDONANTA_PLATA = 'ordonanta_plata';
    case DOVADA_COMUNICARE = 'dovada_comunicare';
    case DOVADA_TAXA_TIMBRU = 'dovada_taxa_timbru';
    case ACT_CONSTATATOR = 'act_constatator';
    case ANEXA = 'anexa';
    case DOVADA = 'dovada';
    case CONTRACT = 'contract';
    case FACTURA = 'factura';
    case BPI_PROOF = 'bpi_proof';
    case EXTRAS_CONT = 'extras_cont';
    case CONFIRMARE_SOLD = 'confirmare_sold';
    case PROCES_VERBAL = 'proces_verbal';
    case COMANDA = 'comanda';
    case NOTIFICARE = 'notificare';
    // Distinct from SOMATIE: that one is generated by the platform and never
    // uploadable, while this is a demand letter the lawyer already sent and
    // now files as evidence.
    case SOMATIE_ANTERIOARA = 'somatie_anterioara';
    /**
     * Proof that the lawyer represents the claimant, filed with the petition. Not
     * evidence of the debt: it says nothing about what is owed, only about who may
     * ask for it on whose behalf.
     */
    case IMPUTERNICIRE_AVOCATIALA = 'imputernicire_avocatiala';
    case ACT_ADITIONAL = 'act_aditional';
    case TITLU_VALOARE = 'titlu_valoare';
    case ALT_DOCUMENT = 'alt_document';

    public function label(): string
    {
        return 'enum.document_type.' . $this->value;
    }

    /**
     * Generate de aplicație prin `AbstractPdfGenerator::generate()` — NU se
     * upload-ează niciodată de avocat ca documente sursă. Single source of
     * truth pentru split UI „Documente generate" vs „Documente sursă" și
     * pentru `CaseFilesPackager` (numerotare top-level vs `anexe/`).
     */
    public function isAutoGenerated(): bool
    {
        return match ($this) {
            self::SOMATIE, self::CERERE_OP, self::OPIS => true,
            default => false,
        };
    }

    /**
     * Uploaded through a dedicated flow, not the generic document modal. The
     * stamp-duty proof carries payment state (status, payer, amount, UAT snapshot)
     * that only `CaseStampDutyController` knows how to record, so offering it in
     * the generic dropdown would silently produce a proof with no payment behind it.
     */
    public function hasDedicatedUploadFlow(): bool
    {
        return $this === self::DOVADA_TAXA_TIMBRU;
    }

    /**
     * Whether the extraction pipeline may classify a document as this type. The power
     * of attorney is excluded: it carries no claim data, so offering it to the
     * classifier only creates a way to mislabel an invoice as a representation act
     * and lose the sums it was uploaded for. It is chosen by the lawyer, never guessed.
     */
    public function isClassifiable(): bool
    {
        return $this !== self::IMPUTERNICIRE_AVOCATIALA;
    }

    /**
     * Pieces the procedure itself imposes, as opposed to evidence the lawyer chooses
     * to annex: the proof that the summons was communicated (CPC art. 1016 para. 2)
     * and the proof that the stamp duty was paid (CPC art. 197). Both gate the filing
     * of the petition, so they must never compete with the contracts and invoices for
     * the per-case attachment cap: a case that reached the cap on evidence would
     * otherwise be unable to attach the very document the gate asks for, turning a
     * product limit into a procedural dead end.
     *
     * The power of attorney joins them: the petition is filed through a representative
     * and the act proving that capacity travels with it, so the cap must not stand
     * between the lawyer and the one document the generation warning asks for.
     */
    public function isProceduralRequirement(): bool
    {
        return match ($this) {
            self::DOVADA_COMUNICARE, self::DOVADA_TAXA_TIMBRU, self::IMPUTERNICIRE_AVOCATIALA => true,
            default => false,
        };
    }

    /**
     * Non-auto-generated types available for lawyer upload. Single source of truth
     * for both the upload form choices and the upload modal options.
     *
     * @return self[]
     */
    public static function uploadableTypes(): array
    {
        return array_values(array_filter(
            self::cases(),
            static fn (self $type): bool => !$type->isAutoGenerated() && !$type->hasDedicatedUploadFlow(),
        ));
    }
}
