<?php

namespace App\Tests\Enum;

use App\Enum\DocumentType;
use PHPUnit\Framework\TestCase;

class DocumentTypeTest extends TestCase
{
    public function testNewLexRecoveryValuesPresent(): void
    {
        $this->assertSame(DocumentType::SOMATIE, DocumentType::from('somatie'));
        $this->assertSame(DocumentType::CERERE_OP, DocumentType::from('cerere_op'));
        $this->assertSame(DocumentType::OPIS, DocumentType::from('opis'));
        $this->assertSame(DocumentType::ORDONANTA_PLATA, DocumentType::from('ordonanta_plata'));
        $this->assertSame(DocumentType::DOVADA_COMUNICARE, DocumentType::from('dovada_comunicare'));
        $this->assertSame(DocumentType::ACT_CONSTATATOR, DocumentType::from('act_constatator'));
        $this->assertSame(DocumentType::ANEXA, DocumentType::from('anexa'));
    }

    public function testKeptValues(): void
    {
        $this->assertSame(DocumentType::DOVADA, DocumentType::from('dovada'));
        $this->assertSame(DocumentType::CONTRACT, DocumentType::from('contract'));
        $this->assertSame(DocumentType::FACTURA, DocumentType::from('factura'));
        $this->assertSame(DocumentType::ALT_DOCUMENT, DocumentType::from('alt_document'));
    }

    public function testCererePdfRemoved(): void
    {
        $this->assertNull(DocumentType::tryFrom('cerere_pdf'));
    }

    public function testAllCasesHaveLabels(): void
    {
        foreach (DocumentType::cases() as $case) {
            $this->assertNotEmpty($case->label());
        }
    }

    /**
     * Pas 5.2 — split UI „Documente generate" vs „Documente sursă":
     * SOMATIE / CERERE_OP / OPIS sunt creează de `AbstractPdfGenerator`;
     * restul sunt uploadate de avocat.
     */
    public function testIsAutoGeneratedFlagsOnlyAppGeneratedTypes(): void
    {
        $this->assertTrue(DocumentType::SOMATIE->isAutoGenerated());
        $this->assertTrue(DocumentType::CERERE_OP->isAutoGenerated());
        $this->assertTrue(DocumentType::OPIS->isAutoGenerated());

        $this->assertFalse(DocumentType::DOVADA_COMUNICARE->isAutoGenerated());
        $this->assertFalse(DocumentType::ORDONANTA_PLATA->isAutoGenerated());
        $this->assertFalse(DocumentType::CONTRACT->isAutoGenerated());
        $this->assertFalse(DocumentType::FACTURA->isAutoGenerated());
        $this->assertFalse(DocumentType::ANEXA->isAutoGenerated());
        $this->assertFalse(DocumentType::DOVADA->isAutoGenerated());
        $this->assertFalse(DocumentType::BPI_PROOF->isAutoGenerated());
        $this->assertFalse(DocumentType::ACT_CONSTATATOR->isAutoGenerated());
        $this->assertFalse(DocumentType::ALT_DOCUMENT->isAutoGenerated());
    }

    public function testOrdonantaPlataIsUploadable(): void
    {
        $this->assertContains(DocumentType::ORDONANTA_PLATA, DocumentType::uploadableTypes());
        $this->assertNotContains(DocumentType::SOMATIE, DocumentType::uploadableTypes());
    }
}
