<?php

declare(strict_types=1);

namespace App\Repository;

use App\Entity\Document;
use App\Entity\LegalCase;
use App\Enum\DocumentType;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/** @extends ServiceEntityRepository<Document> */
class DocumentRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Document::class);
    }

    /**
     * Documents attached to a case, ordered newest first. Used by Tab Documente
     * on the case overview page (Pas 4.0.4) to render the source uploads list.
     *
     * @return Document[]
     */
    public function findByCase(LegalCase $case): array
    {
        return $this->createQueryBuilder('d')
            ->andWhere('d.legalCase = :case')
            ->setParameter('case', $case)
            ->orderBy('d.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }

    /**
     * Documents auto-generate de aplicație (SOMATIE / CERERE_OP / OPIS). Split
     * față de `findSourceByCase()` clarifică UI „Documente generate" vs
     * „Documente sursă (uploadate)" în tab Documente (Pas 5.2).
     *
     * @return Document[]
     */
    public function findGeneratedByCase(LegalCase $case): array
    {
        return $this->findByCaseWithAutoGenerated($case, true);
    }

    /**
     * Documents uploadate de avocat ca anexe sursă (CONTRACT / FACTURA /
     * DOVADA_COMUNICARE / ANEXA / etc.). Exclude tipurile auto-generate.
     *
     * @return Document[]
     */
    public function findSourceByCase(LegalCase $case): array
    {
        return $this->findByCaseWithAutoGenerated($case, false);
    }

    /**
     * Count source attachments only — SOMATIE / CERERE_OP / OPIS must not eat into
     * the per-case upload cap.
     */
    public function countSourceByCase(LegalCase $case): int
    {
        $autoGeneratedTypes = array_values(array_filter(
            DocumentType::cases(),
            static fn (DocumentType $type): bool => $type->isAutoGenerated(),
        ));

        return (int) $this->createQueryBuilder('d')
            ->select('COUNT(d.id)')
            ->andWhere('d.legalCase = :case')
            ->andWhere('d.documentType NOT IN (:types)')
            ->setParameter('case', $case)
            ->setParameter('types', $autoGeneratedTypes)
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @return Document[]
     */
    private function findByCaseWithAutoGenerated(LegalCase $case, bool $autoGenerated): array
    {
        $autoGeneratedTypes = array_values(array_filter(
            DocumentType::cases(),
            static fn (DocumentType $type): bool => $type->isAutoGenerated(),
        ));

        $qb = $this->createQueryBuilder('d')
            ->andWhere('d.legalCase = :case')
            ->setParameter('case', $case)
            ->orderBy('d.createdAt', 'DESC');

        if ($autoGenerated) {
            $qb->andWhere('d.documentType IN (:types)')->setParameter('types', $autoGeneratedTypes);
        } else {
            $qb->andWhere('d.documentType NOT IN (:types)')->setParameter('types', $autoGeneratedTypes);
        }

        return $qb->getQuery()->getResult();
    }

    /**
     * Bulk-attach pre-uploaded documents to a freshly persisted LegalCase.
     *
     * Used by the wizard step 4 submit: documents uploaded in step 0 are
     * persisted with `legalCase = NULL` (fallback path `_pending/{userId}/...`),
     * and only at submit are they linked to the case. Single UPDATE keeps the
     * transaction short — no per-row hydrate.
     *
     * @param int[] $documentIds
     */
    public function attachToCase(array $documentIds, LegalCase $case): int
    {
        if ($documentIds === []) {
            return 0;
        }

        return $this->createQueryBuilder('d')
            ->update()
            ->set('d.legalCase', ':case')
            ->where('d.id IN (:ids)')
            ->setParameter('case', $case)
            ->setParameter('ids', $documentIds)
            ->getQuery()
            ->execute();
    }
}
