<?php

declare(strict_types=1);

namespace App\Tests\Repository;

use App\Entity\Document;
use App\Entity\LegalCase;
use App\Entity\User;
use App\Enum\DocumentType;
use App\Enum\ExtractionStatus;
use App\Repository\DocumentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

/**
 * Pas 5.2 — Tests for DocumentRepository::findSourceByCase + findGeneratedByCase.
 *
 * Verifică split-ul UI „Documente generate" (SOMATIE / CERERE_OP / OPIS) vs
 * „Documente sursă (uploadate)" (CONTRACT / FACTURA / DOVADA_COMUNICARE / etc.)
 * folosind `DocumentType::isAutoGenerated()` ca single source of truth.
 */
final class DocumentRepositoryTest extends KernelTestCase
{
    private EntityManagerInterface $em;
    private DocumentRepository $repository;
    private User $user;
    private LegalCase $case;

    protected function setUp(): void
    {
        self::bootKernel();
        $container = static::getContainer();
        $this->em = $container->get(EntityManagerInterface::class);
        $this->repository = $container->get(DocumentRepository::class);

        $hasher = $container->get(UserPasswordHasherInterface::class);

        $this->user = new User();
        $this->user->setEmail('doc-repo-' . uniqid() . '@test.com');
        $this->user->setPassword($hasher->hashPassword($this->user, 'password'));
        $this->user->setIsVerified(true);
        $this->user->setFirstName('DocRepo');
        $this->user->setLastName('Tester');
        $this->em->persist($this->user);

        $this->case = new LegalCase();
        $this->case->setUser($this->user);
        $this->case->setAmount('1000.00');
        $this->case->setCurrency('RON');
        $this->em->persist($this->case);

        $this->em->flush();
    }

    protected function tearDown(): void
    {
        $userId = $this->user->getId();
        $conn = $this->em->getConnection();
        $conn->executeStatement('DELETE FROM audit_log WHERE user_id = ?', [$userId]);
        $conn->executeStatement('DELETE d FROM legal_deadline d JOIN legal_case lc ON d.legal_case_id = lc.id WHERE lc.user_id = ?', [$userId]);
        $conn->executeStatement('DELETE FROM document WHERE uploaded_by_id = ?', [$userId]);
        $conn->executeStatement('DELETE FROM legal_case WHERE user_id = ?', [$userId]);
        $conn->executeStatement('DELETE FROM `user` WHERE id = ?', [$userId]);
        parent::tearDown();
    }

    private function persistDocument(DocumentType $type, string $filename): Document
    {
        $doc = new Document();
        $doc->setLegalCase($this->case);
        $doc->setDocumentType($type);
        $doc->setOriginalFilename($filename);
        $doc->setStoredFilename('stored-' . uniqid() . '.pdf');
        $doc->setFileSize(1024);
        $doc->setMimeType('application/pdf');
        $doc->setUploadedBy($this->user);
        $doc->setExtractionStatus(ExtractionStatus::COMPLETED);
        $this->em->persist($doc);
        $this->em->flush();

        return $doc;
    }

    public function testFindGeneratedByCaseReturnsOnlyAutoGeneratedTypes(): void
    {
        $this->persistDocument(DocumentType::SOMATIE, 'somatie.pdf');
        $this->persistDocument(DocumentType::CERERE_OP, 'cerere_op.pdf');
        $this->persistDocument(DocumentType::OPIS, 'opis.pdf');
        $this->persistDocument(DocumentType::CONTRACT, 'contract.pdf');
        $this->persistDocument(DocumentType::FACTURA, 'factura.pdf');

        $generated = $this->repository->findGeneratedByCase($this->case);
        $types = array_map(static fn (Document $d): DocumentType => $d->getDocumentType(), $generated);

        self::assertCount(3, $generated);
        self::assertContains(DocumentType::SOMATIE, $types);
        self::assertContains(DocumentType::CERERE_OP, $types);
        self::assertContains(DocumentType::OPIS, $types);
        self::assertNotContains(DocumentType::CONTRACT, $types);
        self::assertNotContains(DocumentType::FACTURA, $types);
    }

    public function testFindSourceByCaseExcludesAutoGeneratedTypes(): void
    {
        $this->persistDocument(DocumentType::SOMATIE, 'somatie.pdf');
        $this->persistDocument(DocumentType::CERERE_OP, 'cerere_op.pdf');
        $this->persistDocument(DocumentType::OPIS, 'opis.pdf');
        $this->persistDocument(DocumentType::CONTRACT, 'contract.pdf');
        $this->persistDocument(DocumentType::FACTURA, 'factura.pdf');
        $this->persistDocument(DocumentType::DOVADA_COMUNICARE, 'AR_recipisa.pdf');

        $source = $this->repository->findSourceByCase($this->case);
        $types = array_map(static fn (Document $d): DocumentType => $d->getDocumentType(), $source);

        self::assertCount(3, $source);
        self::assertContains(DocumentType::CONTRACT, $types);
        self::assertContains(DocumentType::FACTURA, $types);
        self::assertContains(DocumentType::DOVADA_COMUNICARE, $types);
        self::assertNotContains(DocumentType::SOMATIE, $types);
        self::assertNotContains(DocumentType::CERERE_OP, $types);
        self::assertNotContains(DocumentType::OPIS, $types);
    }

    public function testFindSourceByCaseReturnsEmptyArrayWhenNoSourceDocuments(): void
    {
        $this->persistDocument(DocumentType::SOMATIE, 'somatie.pdf');
        $this->persistDocument(DocumentType::OPIS, 'opis.pdf');

        $source = $this->repository->findSourceByCase($this->case);

        self::assertCount(0, $source);
    }

    public function testFindSourceByCaseReturnsAllUploadedDocuments(): void
    {
        $this->persistDocument(DocumentType::CONTRACT, 'a.pdf');
        $this->persistDocument(DocumentType::FACTURA, 'b.pdf');
        $this->persistDocument(DocumentType::ANEXA, 'c.pdf');

        $source = $this->repository->findSourceByCase($this->case);

        self::assertCount(3, $source);
        $filenames = array_map(static fn (Document $d): string => $d->getOriginalFilename(), $source);
        self::assertContains('a.pdf', $filenames);
        self::assertContains('b.pdf', $filenames);
        self::assertContains('c.pdf', $filenames);
    }
}
