<?php

namespace App\Tests\Entity;

use App\Entity\Creditor;
use App\Entity\Debtor;
use App\Entity\LegalCase;
use App\Entity\LegalDeadline;
use App\Entity\User;
use App\Enum\CaseStatus;
use App\Enum\DeadlineType;
use App\Enum\PersonType;
use App\Enum\RelationshipType;
use PHPUnit\Framework\TestCase;

class LegalCaseEntityTest extends TestCase
{
    public function testCaseNumberAutoGeneratedInConstructor(): void
    {
        $case = new LegalCase();

        $this->assertNotEmpty($case->getCaseNumber());
        $this->assertMatchesRegularExpression('/^LR-\d+-\d{4}$/', $case->getCaseNumber());
    }

    public function testCaseNumberIsUniquePerInstance(): void
    {
        $a = new LegalCase();
        $b = new LegalCase();

        $this->assertNotSame($a->getCaseNumber(), $b->getCaseNumber());
    }

    public function testDefaultStatusIsAmiabil(): void
    {
        $case = new LegalCase();

        $this->assertSame(CaseStatus::AMIABIL, $case->getStatus());
    }

    public function testDefaultCurrencyIsRon(): void
    {
        $case = new LegalCase();

        $this->assertSame('RON', $case->getCurrency());
    }

    public function testCollectionsInitializedEmpty(): void
    {
        $case = new LegalCase();

        $this->assertCount(0, $case->getDocuments());
        $this->assertCount(0, $case->getStatusHistory());
        $this->assertCount(0, $case->getPortalEvents());
        $this->assertCount(0, $case->getDebtors());
        $this->assertCount(0, $case->getDeadlines());
    }

    public function testIsDeletedReturnsCorrectValue(): void
    {
        $case = new LegalCase();
        $this->assertFalse($case->isDeleted());

        $case->setDeletedAt(new \DateTimeImmutable());
        $this->assertTrue($case->isDeleted());
    }

    public function testMarkAsDeletedSetsDeletedAt(): void
    {
        $case = new LegalCase();
        $this->assertNull($case->getDeletedAt());

        $case->markAsDeleted();

        $this->assertTrue($case->isDeleted());
        $this->assertNotNull($case->getDeletedAt());
    }

    public function testCreatedAtSetInConstructor(): void
    {
        $before = new \DateTimeImmutable();
        $case = new LegalCase();
        $after = new \DateTimeImmutable();

        $this->assertGreaterThanOrEqual($before->getTimestamp(), $case->getCreatedAt()->getTimestamp());
        $this->assertLessThanOrEqual($after->getTimestamp(), $case->getCreatedAt()->getTimestamp());
    }

    public function testAddDebtorSetsBackReference(): void
    {
        $case = new LegalCase();
        $debtor = new Debtor();
        $debtor->setPersonType(PersonType::PJ);
        $debtor->setName('Debitor SRL');
        $debtor->setAddress('str. X nr. 1');

        $case->addDebtor($debtor);

        $this->assertCount(1, $case->getDebtors());
        $this->assertSame($case, $debtor->getLegalCase());
    }

    public function testAddDeadlineSetsBackReference(): void
    {
        $case = new LegalCase();
        $deadline = new LegalDeadline();
        $deadline->setType(DeadlineType::JUDECATA);
        $deadline->setDeadlineDate(new \DateTime('+30 days'));

        $case->addDeadline($deadline);

        $this->assertCount(1, $case->getDeadlines());
        $this->assertSame($case, $deadline->getLegalCase());
    }

    public function testCreditorAssociation(): void
    {
        $case = new LegalCase();
        $creditor = new Creditor();
        $creditor->setName('SC Creditor SRL');

        $case->setCreditor($creditor);

        $this->assertSame($creditor, $case->getCreditor());
    }

    public function testCoreSetters(): void
    {
        $case = new LegalCase();
        $user = new User();
        $case->setUser($user);
        $case->setStatus(CaseStatus::SOMATIE_TRIMISA);
        $case->setRelationshipType(RelationshipType::COMERCIAL);
        $case->setAmount('5000.00');
        $case->setCalculatedInterest('120.50');
        $case->setStampDuty('200.00');
        $case->setCourtCaseNumber('1234/30/2026');
        $case->setNotes('test note');
        $due = new \DateTime('2026-06-01');
        $case->setDueDate($due);

        $this->assertSame($user, $case->getUser());
        $this->assertSame(CaseStatus::SOMATIE_TRIMISA, $case->getStatus());
        $this->assertSame(RelationshipType::COMERCIAL, $case->getRelationshipType());
        $this->assertSame('5000.00', $case->getAmount());
        $this->assertSame('120.50', $case->getCalculatedInterest());
        $this->assertSame('200.00', $case->getStampDuty());
        $this->assertSame('1234/30/2026', $case->getCourtCaseNumber());
        $this->assertSame('test note', $case->getNotes());
        $this->assertSame($due, $case->getDueDate());
    }

    public function testToStringReturnsCaseNumber(): void
    {
        $case = new LegalCase();

        $this->assertSame($case->getCaseNumber(), (string) $case);
    }
}
